CREATE TABLE IF NOT EXISTS diaporama (
    id INT AUTO_INCREMENT PRIMARY KEY,
    photo_id INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    position INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
